# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be25804783500af1f8962116d7706e37ae6de4d41aa1ea397fce759ce455505dad17757d8c7fafc70e73046fda3def1c8559ed0c1327647fd0b33b9de6f3f581

test:
  secret_key_base: 8f89b6584b4ac2cf445ae8038ce980953e812baa9fe472d8d1068650c9947994ac26a6b8ef122aa9972d314c099f9ab9e66f754d73c859fc4df06038d37dfcc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
